### PR TITLE
various fixes

### PR DESCRIPTION
**Pull request by olofsen**
* fixed "Edit Drugs" crash after "OK"
  - function drugUnitsExpand was gone missing and has now been added to R/drugAndEventDefaults.R
  - also a cell selection problem fixed by removing a hot_rows() in server.R

* "Time until ___" works again
  - in R/simCpCe.R results$Recovery had been set to NULL, but changes in R/simulationPlot.R were needed, especially how to get the labels

* fixed "Log Y axis" crash
  - use only data > 0
  - disable log Y if additional graphs are requested

* "Events" works again; quite a few changes were needed to prevent a warning (and therefore a crash) about incorrect wrap factors

* no arrow and "endCe" text for non-drug graphs

* line type for plasma concentrations now works, the selection used to be overridden

* "Suggest" works again and has a waiter to show that the user has to wait for a result

* fixed some crashes from input in the "Dose Table" and NAs in the plot

* time strings parsed using package lubridate

* if "Reference Time" is "none", times are not converted to hh:mm for times >= 1000

* the drug defaults object was not necessarily present when needed
  - when the gui is created this gave a warning and possibly an email with an error message
  - the new R/drugAndEventDefaults.R obtains both the drug and event defaults with corresponding reactive values in server.R
  - the javascript code had a json tranformation of this object but not necessarily the current one; this is now created in global.R

* prevent multiple clicks on "GO!" butto with Email slide

* routine recalculatePK processes only drugs in the Dose Table
  - the drug selected with "Suggest" is added to the dose table

* hopefully better reactivity of drugs() object so less repetitions of parsing drug information

* the works behind "Suggest" moved to R/suggest.R

* current instead of default dose table in sheet sent by email

* added multiple test routines

* added options in config.yml for maintainer and debugging

* the tryCatchLog function is helpful in finding the location of the line causing an error

* moved sysdata.rda from ./R to ./data

* zipped the original STANPUMP files (and now this is an R project instead of C)

* UNIT_MONTH again set to a rounded value, because this one is used in an url and it is not equal to 1/12 in a test for selecting the correct age unit

* preliminary implementation for oliceridine added

### CODE REVIEW

**Comment by fifteenforty** [comment]
The checks seem to fail because of an authorisation issues. I think I've fixed it.

**Comment by fifteenforty** [comment]
closes #115, closes #102, closes #96, closes #78

**Comment by fifteenforty** [comment]
@olofsen can you please add some more notes to the PR?

**Comment by fifteenforty** [comment]
I think we should just merge this and sort out the deployment issue later.

**Comment by olofsen** [comment]
In the meantime I created a test repository with basically the same deployment script. Without the "forceUpdate = TRUE" argument for rsconnect, I get the same error as in the log above. Note that in that log, the forceUpdate argument is not visible in the backtrace. With the forceUpdate argument, the deployment of the test app works. So perhaps retrying the deployment of stanpumpR now works?

**Comment by olofsen** [comment]
I'm sorry for the noise! On my shinyapps account the deployed app works. Perhaps it doesn't work here because I had expanded the information at config.yml, and I hadn't realized further vars and secrets are then needed for the repository; these changes are visible in shiny-deploy-test.yaml (which also needs to be tidied).

**Comment by olofsen** [comment]
The app deployed to to test now works.

**Comment by fifteenforty** [comment]
Thanks for fixing that. I'll merge this PR! For future PRs, please create an issue, then a branch on your fork (don't use main/master, trust me!). Smaller PRs for one specific issue (whether enhancement or bug) is much easier to check.

**Pull request merged**
